/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.Abrir;
import control.Salvar;
import entidade.Actor;
import entidade.UserCase;
import entidade.Modelo;
import java.awt.Color;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Lucas
 */
public class TextEditor extends javax.swing.JFrame {

    MyHighlightPainter m1 = new MyHighlightPainter(Color.green);
    MyHighlightPainter m2 = new MyHighlightPainter(Color.cyan);
    Modelo modelo;
    private Object doc;

    /**
     * Creates new form TextEditor
     */
    public TextEditor() {
        modelo = new Modelo();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPane1);

        jButton3.setText("Gerar Diagrama");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Gerar Prototipo");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Projeto");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTree1MouseDragged(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        jButton6.setBackground(new java.awt.Color(51, 255, 51));
        jButton6.setText(">>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Árvore do Projeto");

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Abrir...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Salvar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Salvar como...");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Gerar");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jButton6)
                                .addGap(47, 47, 47)
                                .addComponent(jButton8)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int begin = jTextPane1.getSelectionStart();
        int end = jTextPane1.getSelectionEnd();
        Highlighter hilite = jTextPane1.getHighlighter();

        Highlighter.Highlight[] hilites = hilite.getHighlights();

        for (int i = 0; i < hilites.length; i++) {

            int e1 = hilites[i].getEndOffset();
            int b1 = hilites[i].getStartOffset();

            MyHighlightPainter myHighlightPainter = (MyHighlightPainter) hilites[i].getPainter();
            Color c = myHighlightPainter.getColor();
            String sub = "";
            if (c.toString().equals(m1.getColor().toString())) {

                try {
                    sub = jTextPane1.getText(b1, (e1 - b1));
                    Actor ac = new Actor(sub);
                    modelo.addActor(ac);
                } catch (BadLocationException ex) {
                    Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                try {
                    sub = jTextPane1.getText(b1, (e1 - b1));
                    UserCase uc = new UserCase(sub);
                } catch (BadLocationException ex) {
                    Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
        new ListLinker(modelo);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        modelo.setText(jTextPane1.getText());
        JFileChooser selecionador = new JFileChooser();
        selecionador.showSaveDialog(this);
        File arquivo = selecionador.getSelectedFile();

        if (Salvar.salvar(modelo, arquivo) == Salvar.SUCESSO) {
            JOptionPane.showMessageDialog(null, "SUCESSO");
        } else {
            JOptionPane.showMessageDialog(null, "ERRO");
        }

        /**
         * String texto = jTextPane1.getText();
         *
         * Highlighter hilite = jTextPane1.getHighlighter();
         * Highlighter.Highlight[] hilites = hilite.getHighlights();
         *
         * int i = 0; //int numCor = 0; List<Integer> inicioHighLight = new
         * ArrayList<>(); List<Integer> fimHighLight = new ArrayList<>();
         * List<Integer> corHighLight = new ArrayList<>(); //0 = ator 1 = user
         * case
         *
         * try { while (true) { MyHighlightPainter myHighlightPainter =
         * (MyHighlightPainter) hilites[i].getPainter(); Color c =
         * myHighlightPainter.getColor();
         *
         * if (c.toString().equals(m1.getColor().toString())) {
         * corHighLight.add(0); } else if
         * (c.toString().equals(m2.getColor().toString())) {
         * corHighLight.add(1); }
         * inicioHighLight.add(hilites[i].getStartOffset());
         * fimHighLight.add(hilites[i].getEndOffset()); i = i + 1; } } catch
         * (Exception e) { //Nada a fazer. }
         *
         * File arquivo = new File("PosicaoHighLight.txt"); try (FileWriter fw =
         * new FileWriter(arquivo)) {
         *
         * for (int j = 0; j < i; j++) {
         * //System.out.println("Cor = " + corHighLight.get(j) + " Lenght = " + inicioHighLight.get(j) + " ->
         * " + fimHighLight.get(j)); fw.write(corHighLight.get(j) + " " +
         * inicioHighLight.get(j) + " " + fimHighLight.get(j) + "\n"); }
         * fw.close(); } catch (IOException ex) { }
         *
         * File arquivo2 = new File("Texto.txt"); try (FileWriter fw2 = new
         * FileWriter(arquivo2)) { fw2.write(texto); fw2.close(); } catch
         * (IOException ex) { }
         *
         * System.out.print(inicioHighLight); System.out.print("\n" +
         * fimHighLight);
         *
         * System.out.println(texto);
         */
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        resetar();
        JFileChooser selecionador = new JFileChooser();
        selecionador.showOpenDialog(this);
 
        if((modelo = Abrir.abrir(selecionador.getSelectedFile())) != null)
        {
                        System.out.println(""+ modelo.getText());

            JOptionPane.showMessageDialog(this, "SUUUUUUUUCESSOO");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "erro =(");
        }
//        ((MyHighlightPainter) jTextPane1.getHighlighter()).setModelo(modelo);
        jTextPane1.setText(modelo.getText());
        /*       
         try {
        
         jTextPane1.setText("");

         try {
         File file = new File("Texto.txt");
         StringBuffer stringBuffer;
         try (FileReader fileReader = new FileReader(file)) {
         BufferedReader bufferedReader = new BufferedReader(fileReader);
         stringBuffer = new StringBuffer();
         String line;
         while ((line = bufferedReader.readLine()) != null) {
         stringBuffer.append(line);
         stringBuffer.append("\n");
         }
         }
         jTextPane1.setText(stringBuffer.toString());
         System.out.println("Contents of file:");
         System.out.println(stringBuffer.toString());
         } catch (IOException e) {
         e.printStackTrace();
         }

         Scanner scanner = new Scanner(new FileReader("PosicaoHighLight.txt"));
         while (scanner.hasNext()) {
         try {
         int tipoMarcacao = scanner.nextInt();
         int inicio = scanner.nextInt();
         int fim = scanner.nextInt();
         if (tipoMarcacao == 0) {
         jTextPane1.getHighlighter().addHighlight(inicio, fim, m1);
         } else {
         jTextPane1.getHighlighter().addHighlight(inicio, fim, m2);
         }

         System.out.println(inicio + " " + fim + "\n");
         } catch (Exception e) {

         }

         }
         } catch (FileNotFoundException ex) {
         Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
         }
         */
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTree1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseDragged

    }//GEN-LAST:event_jTree1MouseDragged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Remover Ator ou Caso de Uso
        try {
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode selectNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
            if (selectNode.isRoot()) {
                JOptionPane.showMessageDialog(null, "Não é possível remover a raiz do projeto.", "Alerta", JOptionPane.WARNING_MESSAGE);
            } else {
                model.removeNodeFromParent(selectNode);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer a removeção.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Adicionar Ator
        try {
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode selectNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
            DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(jTextPane1.getSelectedText());
            model.insertNodeInto(newNode, selectNode, 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nenhum nó foi selecionado.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    public void resetar() {
        jTextPane1.setText("");
        modelo = new Modelo();
    }

    public void removeHighlights(JTextComponent textComp) {
        Highlighter hilite = textComp.getHighlighter();
        Highlighter.Highlight[] hilites = hilite.getHighlights();
        for (int i = 0; i < hilites.length; i++) {
            if (hilites[i].getPainter() instanceof MyHighlightPainter) {
                hilite.removeHighlight(hilites[i]);
            }
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
